; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=slp-vectorizer -S | FileCheck %s

; Regression test for issue #69894.
; The SLP vectorizer should not crash when handling externref values.
; WebAssembly reference types (externref/funcref) are now represented as
; TargetExtType which cannot be vectorized (VectorType::isValidElementType
; returns false for TargetExtType).

target datalayout = "e-m:e-p:32:32-i64:64-i128:128-n32:64-S128-ni:1"
target triple = "wasm32-unknown-unknown"

%externref = type target("wasm.externref")

define hidden void @test(i32 noundef %flag, %externref %ref1, %externref %ref2) #0 {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[FLAG:%.*]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[IF_END:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[CALL:%.*]] = tail call target("wasm.externref") @foo()
; CHECK-NEXT:    [[CALL1:%.*]] = tail call target("wasm.externref") @foo()
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[REF1_ADDR_0:%.*]] = phi target("wasm.externref") [ [[CALL]], [[IF_THEN]] ], [ [[REF1:%.*]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[REF2_ADDR_0:%.*]] = phi target("wasm.externref") [ [[CALL1]], [[IF_THEN]] ], [ [[REF2:%.*]], [[ENTRY]] ]
; CHECK-NEXT:    tail call void @bar(target("wasm.externref") [[REF1_ADDR_0]])
; CHECK-NEXT:    tail call void @bar(target("wasm.externref") [[REF2_ADDR_0]])
; CHECK-NEXT:    ret void
;
entry:
  %tobool.not = icmp eq i32 %flag, 0
  br i1 %tobool.not, label %if.end, label %if.then

if.then:
  %call = tail call %externref @foo()
  %call1 = tail call %externref @foo()
  br label %if.end

if.end:
  %ref1.addr.0 = phi %externref [ %call, %if.then ], [ %ref1, %entry ]
  %ref2.addr.0 = phi %externref [ %call1, %if.then ], [ %ref2, %entry ]
  tail call void @bar(%externref %ref1.addr.0)
  tail call void @bar(%externref %ref2.addr.0)
  ret void
}

declare %externref @foo()

declare void @bar(%externref)

attributes #0 = { nounwind "target-cpu"="generic" "target-features"="+reference-types" }
