// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %clang_cc1 -triple wasm32 -target-feature +reference-types -disable-O0-optnone -emit-llvm %s -o - | opt -S -passes=mem2reg | FileCheck %s
// REQUIRES: webassembly-registered-target

typedef void (*__funcref fn_funcref)(void);
static fn_funcref ftable[0];

// CHECK-LABEL: define {{[^@]+}}@test_funcref_table_get
// CHECK-SAME: (i32 noundef [[I:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call ptr addrspace(20) @llvm.wasm.table.get.funcref(ptr addrspace(1) @ftable, i32 [[I]])
// CHECK-NEXT:    ret ptr addrspace(20) [[TMP0]]
//
fn_funcref test_funcref_table_get(int i) {
  return __builtin_wasm_table_get(ftable, i);
}

// CHECK-LABEL: define {{[^@]+}}@test_funcref_table_set
// CHECK-SAME: (i32 noundef [[I:%.*]], ptr addrspace(20) noundef [[REF:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.wasm.table.set.funcref(ptr addrspace(1) @ftable, i32 [[I]], ptr addrspace(20) [[REF]])
// CHECK-NEXT:    ret void
//
void test_funcref_table_set(int i, fn_funcref ref) {
  __builtin_wasm_table_set(ftable, i, ref);
}
